version: '3.8'
services:
  # Service for backend API
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      # MongoDB connection string
      - MONGO_URI=mongodb://mongo:27017/hotel_booking
    depends_on:
      - mongo
    restart: always  # Restart policy to ensure service availability
  # Service for frontend application
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    restart: always  # Restart policy to ensure service availability
  # Service for MongoDB database
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always  # Restart policy to ensure service availability
    healthcheck:
      test: [ 'CMD', 'mongo', '--eval', 'db.adminCommand("ping")' ]
      interval: 30s
      timeout: 10s
      retries: 5